"""Reproduce every number in the README from the committed example files.

    python scripts/evaluate.py            # prints the tables as Markdown
    python scripts/evaluate.py --per-class

No model is run: `examples/*/prelabel/` holds the recorded outputs of
`panoptic-prelabel prelabel` (Mask R-CNN instances and MobileSAM regions) for
each photo, so the automatic part is replayed from there with `refine`.

Three measurements, all against the same reference, the human-corrected map
(`resolve` on `examples/*/cvat_corrected.zip`):

1. Automatic pre-annotation vs corrected: how much manual correction changed.
2. Region naming: the class written in `regions.yaml` for each MobileSAM region
   vs the class the corrected map gives most of that region's pixels.
3. This code vs the first (July 2026) version, on the same CVAT exports.

The reference is one person's correction, and it was made starting from
pre-labels of an earlier version whose region names were also chosen by
Claude. Read the numbers as agreement with that correction, not as accuracy
against independent ground truth.
"""

from __future__ import annotations

import argparse
import shutil
import tempfile
from collections import Counter
from pathlib import Path

import numpy as np
import yaml

from panoptic_prelabel.coco_io import read_coco
from panoptic_prelabel.compare import Evaluation, evaluate, format_report
from panoptic_prelabel.config import Config
from panoptic_prelabel.panoptic import Panoptic, read_panoptic
from panoptic_prelabel.pipeline import IGNORE, assign_labels, read_regions, refine
from panoptic_prelabel.resolve import resolve

ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"


def groups_of(scene: Path) -> list[list[int]]:
    f = scene / "scene.yaml"
    return yaml.safe_load(f.read_text())["groups"] if f.exists() else []


def corrected_map(scene: Path, cfg: Config) -> Panoptic:
    return resolve(read_coco(scene / "cvat_corrected.zip"), cfg, groups=groups_of(scene))


def automatic_map(scene: Path, cfg: Config, tmp: Path) -> Panoptic:
    work = tmp / scene.name
    shutil.copytree(scene / "prelabel", work)
    refine(work, cfg, labels=scene / "regions.yaml")
    return resolve(read_coco(work / "coco_for_cvat.zip"), cfg)


def class_map(pan: Panoptic) -> np.ndarray:
    lut = np.array([""] * (int(pan.id_map.max()) + 1), dtype=object)
    for s in pan.segments:
        lut[s.id] = s.category
    return lut[pan.id_map]


def region_naming(scene: Path, ref: Panoptic, cfg: Config) -> list[tuple[str, str, int]]:
    """(label written, majority reference class, region area) for every named region."""
    regions = read_regions(scene / "prelabel")
    labels = assign_labels(regions, scene / "regions.yaml", cfg, allow_unlabeled=True)
    ref_cls = class_map(ref)
    rows = []
    for rid, label in sorted(labels.items()):
        if label == IGNORE:
            continue
        pixels = ref_cls[regions.label_map == rid]
        majority, _ = Counter(pixels.tolist()).most_common(1)[0]
        rows.append((label, majority, int(pixels.size)))
    return rows


def pct(x: float) -> str:
    return f"{100 * x:.1f}"


def table(ev_rows: list[tuple[str, Evaluation]]) -> str:
    out = ["| images | PQ | PQ things | PQ stuff | mIoU | pixel accuracy |", "|---|---|---|---|---|---|"]
    for name, ev in ev_rows:
        s = ev.summary()
        out.append(
            f"| {name} | {pct(s['PQ'])} | {pct(s['PQ_th'])} | {pct(s['PQ_st'])} | {pct(s['mIoU'])} "
            f"| {100 * s['pixel_acc']:.2f} % |"
        )
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-class", action="store_true")
    args = ap.parse_args()
    cfg = Config.load()
    scenes = sorted(p for p in EXAMPLES.iterdir() if (p / "cvat_corrected.zip").exists())

    refs = {s.name: corrected_map(s, cfg) for s in scenes}
    with tempfile.TemporaryDirectory() as tmp:
        autos = {s.name: automatic_map(s, cfg, Path(tmp)) for s in scenes}
    julys = {s.name: read_panoptic(s / "reference_2026-07" / "panoptic.json") for s in scenes}

    print("# Results\n")
    print("Generated by `python scripts/evaluate.py` from the committed example files; do not edit by hand.")
    print("CI regenerates this file and fails if it differs.\n")
    print("## 1. Automatic pre-annotation vs human-corrected\n")
    rows = [(n, evaluate([(refs[n], autos[n])])) for n in refs]
    rows.append((f"all {len(refs)}, pooled", evaluate([(refs[n], autos[n]) for n in refs])))
    print(table(rows))
    if args.per_class:
        print("\n```\n" + format_report(rows[-1][1], per_class=True) + "\n```")

    print("\n## 2. Region naming vs human-corrected\n")
    all_rows = []
    print("| images | regions named | same class as the correction | pixel-weighted |")
    print("|---|---|---|---|")
    for s in scenes:
        r = region_naming(s, refs[s.name], cfg)
        all_rows += r
        ok = [lab == maj for lab, maj, _ in r]
        w = sum(a for (_, _, a), k in zip(r, ok, strict=True) if k) / sum(a for *_, a in r)
        print(f"| {s.name} | {len(r)} | {sum(ok)} ({100 * sum(ok) / len(r):.0f} %) | {100 * w:.1f} % |")
    ok = [lab == maj for lab, maj, _ in all_rows]
    w = sum(a for (_, _, a), k in zip(all_rows, ok, strict=True) if k) / sum(a for *_, a in all_rows)
    print(f"| all | {len(all_rows)} | {sum(ok)} ({100 * sum(ok) / len(ok):.0f} %) | {100 * w:.1f} % |")
    errors = Counter((lab, maj) for lab, maj, _ in all_rows if lab != maj)
    area = Counter()
    for lab, maj, a in all_rows:
        if lab != maj:
            area[(lab, maj)] += a
    print("\nDisagreements (label written → class in the correction: regions, pixels):")
    for (lab, maj), n in errors.most_common():
        print(f"- {lab} → {maj}: {n}, {area[(lab, maj)]} px")

    print("\n## 3. This code vs the July 2026 version (same CVAT exports)\n")
    rows = [(n, evaluate([(julys[n], refs[n])])) for n in refs]
    rows.append((f"all {len(refs)}, pooled", evaluate([(julys[n], refs[n]) for n in refs])))
    print(table(rows))


if __name__ == "__main__":
    main()
